---

:project:
  :use_exceptions: TRUE
  :use_test_preprocessor: :tests
  :build_root: build
  :release_build: TRUE
  :test_file_prefix: test_
  :which_ceedling: gem
  :ceedling_version: 1.0.1
  :compile_threads: 16
  :default_tasks:
    - test:all

:environment:

:extension:
  :executable: .out

:paths:
  :test:
    - +:test/**
    - -:test/support
  :source:
    - src/**
  :include:
    - src/**
    - inc/**
    - ports/**
    - -:ports/extra/**
  :support:
    - test/support
  :libraries: []

:defines:
  :test:
    :*:
      - TEST
    :test_u_cx_at_client_no_urc_queue:
      - U_CX_USE_URC_QUEUE=0

:cmock:
  :mock_prefix: mock_
  :when_no_prototypes: :warn
  :enforce_strict_ordering: TRUE
  :plugins:
    - :ignore
    - :callback
    - :expect_any_args
    - :ignore_arg
    - :return_thru_ptr
  :treat_as:
    uint8:    HEX8
    uint16:   HEX16
    uint32:   UINT32
    int8:     INT8
    bool:     UINT8
    uPortUartHandle_t: HEX32
  :includes:
  :treat_externs: :include
  :strippables:
    - '(?:uPortBgRxTaskCreate|uPortBgRxTaskDestroy)\s*\([^)]*\)'

:module_generator:
  :project_root: ./
  :source_root: src/
  :inc_root: inc/
  :test_root: test/
  :naming: snake

:gcov:
  :reports:
    - HtmlDetailed
  :gcovr:
    :html_medium_threshold: 75
    :html_high_threshold: 90

:report_tests_log_factory:
  :reports:
    - cppunit
    - junit
  :junit:
    :filename: report_junit.xml

:libraries:
  :placement: :end
  :flag: "-l${1}"
  :path_flag: "-L ${1}"
  :system: []
  :test: []
  :release: []

:plugins:
  :load_paths: []
  :enabled:
    - report_tests_pretty_stdout
    - module_generator
    - gcov
    - report_tests_log_factory

:flags:
  :test:
    :preprocess:
      :*:
        - -DU_CX_PORT_HEADER_FILE=\"u_port_test.h\"
    :compile:
      :*:
        - -DU_CX_PORT_HEADER_FILE=\"u_port_test.h\"
        - -Werror
        - -Wall
        - -Wextra
        - -fsanitize=address
        - -fsanitize=undefined
        - -fsanitize-address-use-after-scope
        - -fno-sanitize-recover
        - -fstack-protector-all
        - -fno-omit-frame-pointer
        - -O1
        - -Wno-clobbered
    :link:
      :*:
        - -fsanitize=address
        - -fsanitize=undefined
        - -fsanitize-address-use-after-scope
        - -fno-sanitize-recover
        - -lpthread
  :gcov:
    :compile:
      - -DU_CX_PORT_HEADER_FILE=\"u_port_test.h\"
      - -Werror
      - -Wall
      - -Wextra
      - -fsanitize=address
      - -fsanitize=undefined
      - -fsanitize-address-use-after-scope
      - -fno-sanitize-recover
      - -fstack-protector-all
      - -fno-omit-frame-pointer
      - -O1
      - -Wno-clobbered
    :link:
      - -fsanitize=address
      - -fsanitize=undefined
      - -fsanitize-address-use-after-scope
      - -fno-sanitize-recover
      - -lpthread